export const TEESHEET_CLUBS: { id: number; name: string }[] = [
    { id: 59, name: "* Clubmaster  Test Club" },
    { id: 74, name: "Atlantic Beach Links" },
    { id: 112, name: "Babirwa Game Lodge" },
    { id: 78, name: "Bankenveld Golf Club" },
    { id: 73, name: "Bellville Golf Club" },
    { id: 102, name: "Blair Atholl" },
    { id: 82, name: "Bloemfontein Golf Club" },
    { id: 39, name: "Blue Valley Golf Estate" },
    { id: 134, name: "Bluetree World Of Golf" },
    { id: 52, name: "Bonanza Golf Course" },
    { id: 122, name: "Borrowdale Brooke Golf Club" },
    { id: 186, name: "Boschhoek Golf Club" },
    { id: 177, name: "Bredasdorp Golf Club" },
    { id: 63, name: "Centurion Country Club" },
    { id: 148, name: "Chapman Golf Club" },
    { id: 58, name: "Clarens Golf Estate" },
    { id: 2, name: "Clovelly Country Club" },
    { id: 86, name: "CMR Golf Club" },
    { id: 124, name: "Cotswold Downs Golf Club" },
    { id: 166, name: "Country Club Harare" },
    { id: 32, name: "Dainfern Country Club" },
    { id: 188, name: "De Zalze Golf Estate" },
    { id: 93, name: "Durban CC" },
    { id: 3, name: "Durbanville Golf Club" },
    { id: 106, name: "Eagle Canyon" },
    { id: 50, name: "Ebotse Golf Links" },
    { id: 144, name: "Elements Private Golf Reserve" },
    { id: 60, name: "Emfuleni Golf Club" },
    { id: 101, name: "Erinvale Golf Club" },
    { id: 137, name: "Ermelo Golf Club" },
    { id: 121, name: "ERPM Golf Club" },
    { id: 65, name: "Euphoria Golf & Lifestyle Estate" },
    { id: 1, name: "George Golf Club" },
    { id: 145, name: "Germiston Golf Club" },
    { id: 162, name: "Goose Valley Golf Club" },
    { id: 147, name: "Gowrie Farm Golf Club" },
    { id: 175, name: "Helderberg Village Golf Club" },
    { id: 4, name: "Hermanus Golf Club" },
    { id: 161, name: "Heron Banks Golf Club" },
    { id: 34, name: "Highland Gate Golf Club (Dullstroom)" },
    { id: 90, name: "Houghton GC" },
    { id: 16, name: "Humewood Golf Club" },
    { id: 5, name: "Irene Country Club" },
    { id: 91, name: "Jackal Creek" },
    { id: 23, name: "Jeffreys Bay Golf Club" },
    { id: 165, name: "Kambaku Golf Club" },
    { id: 157, name: "Kameeldoring Golf Club" },
    { id: 169, name: "Kansanshi Golf Club" },
    { id: 110, name: "Killarney Country Club" },
    { id: 153, name: "Kimberley Golf Club" },
    { id: 51, name: "King David Mowbray Golf Club" },
    { id: 178, name: "Kingswood Golf Club" },
    { id: 76, name: "Kleinmond Golf Club" },
    { id: 46, name: "Klerksdorp Golf Club" },
    { id: 20, name: "Knysna Golf Club" },
    { id: 111, name: "Koro Creek Golf Estate" },
    { id: 150, name: "Krugersdorp Golf Club" },
    { id: 6, name: "Kuilsrivier Golf Club" },
    { id: 81, name: "Kyalami Country Club" },
    { id: 24, name: "Langebaan Country Estate" },
    { id: 183, name: "Legends Golf Club" },
    { id: 119, name: "Lusaka Golf Club" },
    { id: 127, name: "Maccauvlei Golf Club" },
    { id: 49, name: "MagaliesPark" },
    { id: 138, name: "Malelane Golf Club" },
    { id: 117, name: "Malmesbury Golf Club" },
    { id: 88, name: "Marblehall Golf Club" },
    { id: 142, name: "Margate Country Club" },
    { id: 17, name: "Mbombela Golf Club" },
    { id: 84, name: "Metropolitan Golf Club" },
    { id: 107, name: "Middleburg Country Club" },
    { id: 71, name: "Milnerton Golf Club" },
    { id: 131, name: "Modderfontein Golf Club" },
    { id: 54, name: "Mont Choisy Le Golf" },
    { id: 80, name: "Mooinooi Golf Club" },
    { id: 31, name: "Mossel Bay Golf Club" },
    { id: 28, name: "Mount Edgecombe" },
    { id: 120, name: "Olivewood Golf Estate" },
    { id: 135, name: "Oppenheimer Golf Club" },
    { id: 95, name: "Orkney Golf Club" },
    { id: 158, name: "Oudtshoorn Golf Club" },
    { id: 149, name: "Paarl Golf Club" },
    { id: 18, name: "Parkview Golf Club" },
    { id: 70, name: "Parow Golf Club" },
    { id: 98, name: "Pebble Rock Golf Club" },
    { id: 168, name: "Pebble Rock Padel" },
    { id: 22, name: "Pecanwood Country Club" },
    { id: 159, name: "Pezula Golf Club" },
    { id: 45, name: "Pinnacle Point" },
    { id: 40, name: "Plettenberg Bay Golf Club" },
    { id: 99, name: "Polokwane Golf Club" },
    { id: 19, name: "Port Elizabeth Golf Club" },
    { id: 156, name: "Port Shepstone Country Club" },
    { id: 11, name: "Potchefstroom Golf Club" },
    { id: 68, name: "Pretoria Country Club" },
    { id: 89, name: "Princes Grant Golf Estate" },
    { id: 113, name: "Richards Bay Country Club" },
    { id: 105, name: "Riversdal Golf Club" },
    { id: 48, name: "Riviera on Vaal Country Club" },
    { id: 130, name: "Robertson Golf Club" },
    { id: 55, name: "Royal Cape Golf Club" },
    { id: 72, name: "Royal Johannesburg" },
    { id: 140, name: "Royal Port Alfred Golf Club" },
    { id: 146, name: "Ruimsig Country Club" },
    { id: 83, name: "San Lameer" },
    { id: 163, name: "Sandy Lane Golf Club" },
    { id: 43, name: "Schoemanpark Golf Club" },
    { id: 139, name: "Seasons Golf Club" },
    { id: 100, name: "Serengeti Golf Estate" },
    { id: 69, name: "Services Golf Club" },
    { id: 123, name: "Shelley Point Golf Club" },
    { id: 170, name: "Silver Lakes Golf & Wildlife Estate" },
    { id: 7, name: "Simbithi Country Club" },
    { id: 21, name: "Somerset West Golf Club" },
    { id: 160, name: "Southbroom Golf Club" },
    { id: 126, name: "Soweto Country Club" },
    { id: 77, name: "Springs Golf Club" },
    { id: 96, name: "St Francis Bay GC" },
    { id: 67, name: "St Francis Links" },
    { id: 44, name: "State Mines Country Club" },
    { id: 12, name: "Stellenbosch Golf Club" },
    { id: 152, name: "Stilbaai Golf Club" },
    { id: 15, name: "Strand Golf Club" },
    { id: 38, name: "The Belmont GC" },
    { id: 179, name: "The Lake Club Benoni" },
    { id: 143, name: "Trident Country Club" },
    { id: 141, name: "Umdoni Park Golf Club" },
    { id: 57, name: "Victoria Country Club" },
    { id: 66, name: "Walmer Golf Club" },
    { id: 64, name: "Waterkloof Golf Club" },
    { id: 118, name: "Wedgewood Golf Club" },
    { id: 129, name: "Wellington Golf Club" },
    { id: 94, name: "Westbank Golf Club" },
    { id: 62, name: "Westlake Golf Club" },
    { id: 108, name: "White River CC" },
    { id: 189, name: "Wingate Park GC - Harare" },
    { id: 9, name: "Worcester Golf Club" },
    { id: 56, name: "Zululand Yacht Club" },
    { id: 61, name: "Zwartkop Country Club" },
    { id: 164, name: "ZZ Test Country Club" },
];
